### ISSUE TITLE
How to set width  filled Size of screen

### ISSUE THREAD

**Issue by IxfianIshant** [radusalagean/info-bar-compose#4]
i want to set width with full size of screen without padding

**Comment by radusalagean** [comment]
I assume you are currently using the Standard InfoBar composable and can't get rid of the horizontal inner-padding. In order to have control over this, switch to the Generic InfoBar option, described in the [`readme` file](https://github.com/radusalagean/info-bar-compose#using-the-generic-composable).

Here is a simple example that doesn't use any padding and fills all the available width of the root view with text:

1. Extend the BaseInfoBarMessage abstract class and define your custom message data structure:
```kotlin
class CustomMessage(
    val textString: String
) : BaseInfoBarMessage() {
    override val containsControls: Boolean = false
}
```
2. Declare the content composable that defines your layout:
```kotlin
val content: @Composable (CustomMessage) -> Unit = { message ->
    Text(
        modifier = Modifier.fillMaxWidth()
            .background(color = Color.Black),
        text = message.textString,
        color = Color.White
    )
}
```
3. Display the message:
```kotlin
Box(
    Modifier.fillMaxSize()
) {
    // Place the InfoBar in the root container composable of your screen, so it can fill the entire width
    var customMessage: CustomMessage? by remember {
        mutableStateOf(null)
    }
    InfoBar( // Generic InfoBar
        modifier = Modifier.fillMaxWidth(),
        offeredMessage = customMessage,
        shape = RectangleShape,
        content = content,
        onDismiss = {
            customMessage = null
        }
    )
}
```

Then trigger the message whenever needed, like when receiving an API response or inside a click listener:
```kotlin
Button(
    onClick = { 
        customMessage = CustomMessage(
            textString = "This is a custom message"
        )
    }
) {
    Text("Show message")
}
```

**Comment by IxfianIshant** [comment]
thanks
